### ISSUE TITLE
Equals for Floats/Bools/Ints

### ISSUE THREAD

**Issue by elehman16** [mlanotte1998/SoftDevApi#11]
Here is an example of one of the tests for boolean (line 141): t_true(a1->get(1)->equals(false));

The get function should return a boolean, which is a primitive and has no ->equals function. The proper comparisons should be made.

**Comment by mlanotte1998** [comment]
valid point, sorry I was pretty much just copying in pasting

**Comment by mlanotte1998** [comment]
should be good now
