### ISSUE TITLE
Testing Issues

### ISSUE THREAD

**Issue by Kenright12345** [mlanotte1998/SoftDevApi#12]
Line 87 - error: ‘o1’ was not declared in this scope
Line 148 - One extra parenthesis
Line 175 - BoolArray a3 = new BoolArray(); declaration needs to be BoolArray * a3
Line 193 - Missing ==
Line 225 - IntArray a3 = new IntArray(); declaration needs to be IntArray * a3
Line 263 - IntArray *a2 = new IntArray(); This is in the FloatArray test method need to be
FloatArray * a2 = new FloatArray()
Line 275 - FloatArray a3 = new FloatArray(); declaration needs to be FloatArray * a3

Thanks!

**Comment by mlanotte1998** [comment]
Hey sorry about those, I'm not compiling it cause I don't obviously have an implementation so I don't have anything to tell me about the compile errors. I think I fixed all of those problems now
