### ISSUE TITLE
test array 173, 174

### ISSUE THREAD

**Issue by elehman16** [mlanotte1998/SoftDevApi#13]
Lines 173, 174 contradict each other?
    t_false(a1->equals(a2));
    t_true(a1->equals(a2));

**Comment by elehman16** [comment]
I closed it because I confused myself... Sorry! The first one is correct. The second test should be there.

**Comment by elehman16** [comment]
Same with lines 228, 279.

**Comment by mlanotte1998** [comment]
I just updated it
