### ISSUE TITLE
Testing Floats

### ISSUE THREAD

**Issue by elehman16** [mlanotte1998/SoftDevApi#14]
I believe for float testing, it's best practice to do some sort of subtraction and see if the difference is less than an epsilon. Could the tests be updated to reflect this. Also on line #2, there is #include "sbject.h" -> and it should be #include "object.h".

**Comment by elehman16** [comment]
I am making a PR. Will add soon (along with other changes to test file).

**Comment by mlanotte1998** [comment]
Thanks, I merged it
