### ISSUE TITLE
Consistent Object and String

### ISSUE THREAD

**Issue by Kenright12345** [mlanotte1998/SoftDevApi#2]
Would you be opposed to using the piazza post @166 implementation of String and Object?

**Comment by mlanotte1998** [comment]
I'll make the change sometime tonight

**Comment by mlanotte1998** [comment]
Sorry I was a little late on the change, I just uploaded the new Object and String, and I should have the tests fixed in a little while to reflect the changes.

**Comment by mlanotte1998** [comment]
I would also look at the other issue on this to see another change that is going to be made.

**Comment by mlanotte1998** [comment]
Someone posted a String and Object that is simpler then what Vitek did for the whole class @345 , so I think I am going to change it to that tonight

**Comment by elehman16** [comment]
See the issue that I raised. You likely won't have to change your object and string if you remove the tests in test-array.cpp.

**Comment by mlanotte1998** [comment]
I'm using the more common string and object from piazza now and updated the tests
