### ISSUE TITLE
Hierarchy 

### ISSUE THREAD

**Issue by LalBirali** [mlanotte1998/SoftDevApi#3]
Quick q, how do you feel about just using a list of Object pointers, and having a hierarchy system: STRING -> FLOAT -> INT -> BOOL versus having 4 implementations and 4 boxed classes of string, float, int, and bool? Wondering what your thoughts are?

**Comment by mlanotte1998** [comment]
I'm not quite sure what that implementation would act like. Can you describe it more?

**Comment by LalBirali** [comment]
don't know if your class had this discussion about having 4 separate Array classes or having the Object* just be the Array Type, and then have users able to add a Boxed class (String, Int, Bool, Float) where casting would be used. Essentially, like lets say we added Bools (so, in essence, we have a BoolArray), but then we had 12.5. Then everything in this BoolArray should be recast to Float, as it has a higher priority, so effectively it would know be a FloatArray. And you can get the type of the Array via an enum or class enum. Just a thought? To reduce code duplication

**Comment by mlanotte1998** [comment]
So really its an array of strings and each string always keeps track of whether what is inside is a String, int bool, or float?

**Comment by mlanotte1998** [comment]
Or is there one single "Boxed" class , call it whatever that is an object and that thing holds a string, int, bool, or float somehow?

**Comment by LalBirali** [comment]
That could be possible? I'm not entirely sure what would be the optimal solution or the least amount of work for all of us, like the tradeoff between code duplication and casting a large amount, you know what i mean? But preferably, it'd be boxed?

**Comment by mlanotte1998** [comment]
Okay I'll make the change sometime today, its mostly just getting rid of the type field and changing the descriptions of functions and leaving how you wish to implement the objects more up to you.

**Comment by mlanotte1998** [comment]
The change was made.

**Comment by mlanotte1998** [comment]
Hey, one of the other groups made good points about how this implementation didn't technically allow for adding floats, ints, and bools and for testing those so I made a change to have 4 types of arrays, one for objects, and then one for each of the primitives and they all extend object. Let me know if this causes any big issues
