### ISSUE TITLE
Array Fields

### ISSUE THREAD

**Issue by elehman16** [mlanotte1998/SoftDevApi#5]
I believe fields are considered an implementation detail, which unfortunately means you will likely need to get rid of them, and purge them from git history.

**Comment by mlanotte1998** [comment]
I just uploaded a new version of the file without it. why would I need to purge that from the git history

**Comment by elehman16** [comment]
I have no clue :( ... But it's on Piazza:

Q: What if there is already an implementation in the spec? 
A: Let the spec team know that if they don't remove it, they will lose points. Further, they need to purge it from the history. `git rm` is not nearly enough. Also, please write up this incident as a part of your report.
