### ISSUE TITLE
Testing Float/Int/Bool

### ISSUE THREAD

**Issue by elehman16** [mlanotte1998/SoftDevApi#6]
We saw your previous comment about the changes you made to incorporate Floats, Bools, and Integers into the design. However, these need to be tested. Would it be possible to have the corresponding tests to be added to the test-array.cpp class?

**Comment by mlanotte1998** [comment]
Well being able to pass primitives to the array is impossible, so wouldn't the float/bool/int stuff be up to your implementation?

**Comment by elehman16** [comment]
I don't think we are allowed to modify the test file at all :/ I agree that it *should* be up to us, but I actually don't think it is (since we need tests). I believe you need to decide about what classes to add (i.e. https://piazza.com/class/k51bluky59n2jr?cid=331). Also look at the first follow up where they ask about tests.

**Comment by mlanotte1998** [comment]
I've spent an hour deciding what I want to do for the spec I was given because of how vague it is so I'm not sure yet what to do. My current idea has to do with putting the primitives in a string object and somehow parsing them out but I don't know if that really makes sense.

**Comment by elehman16** [comment]
I agree that it is super vague. I would say that pretty much anything you come up with will be reasonable, so I would just pick something and go for it!

**Comment by mlanotte1998** [comment]
So let's say I decide to go the less memory efficient route and do the four classes , string, bool, int, and float. Do I need to add header files for those classes or just mention objects called those in the test files?

**Comment by elehman16** [comment]
I would say that you *probably* would want to define specs in the array.h file (for bool/int/float), and then generically use those in your tests. I would also ask on Piazza.

**Comment by mlanotte1998** [comment]
Okay I've been talking with someone else and I think I am going to change it to have more array classes ( a Bool, Float, and Int array) and fix the tests. I'll do that tonight

**Comment by mlanotte1998** [comment]
Hey so I made the change, and also added a lot of tests Let me know if there are any issues with them.

**Comment by elehman16** [comment]
I'm supposed to do 1 issue per request, so I'll close this issue and open another one (should hopefully be a simple fix).
