### ISSUE TITLE
Test - Main

### ISSUE THREAD

**Issue by Kenright12345** [mlanotte1998/SoftDevApi#9]
Can you add calls to all of the test methods in the main() for test? Thanks!

**Comment by Kenright12345** [comment]
We also named our classes with lower cases (array.h, object.h, string.h). Can you make these changes in the #includes for the test file. You also used the following in the test file to make an array:
Array *a2 = new Array(o1); (Line 62) (Possibly in other locations for int, float, string, bool arrays)
There is no matching constructor that takes in an object. Can you change the way the array is constructed or add the constructor? Thanks!

**Comment by Kenright12345** [comment]
There is also a missing semicolon on line 73!

**Comment by mlanotte1998** [comment]
It should be all set now
